#ifndef SHADERLAYOUT_H
#define SHADERLAYOUT_H

#define S_UNIFORM_MATMODELVIEW "matmodelview"
#define S_UNIFORM_MATPROJECTION "matprojection"

#define S_VERTEX_ATTRIB_POSITION 0
#define S_VERTEX_ATTRIB_NORMAL 1
#define S_VERTEX_ATTRIB_COLOR 2
#define S_VERTEX_ATTRIB_TEXCOORD 3
#define S_VERTEX_ATTRIB_TANGENT 4
#define S_VERTEX_ATTRIB_BITANGENT 5
#define S_VERTEX_ATTRIB_PARAM 6

#endif